name: Tests
on:
  push:
  schedule:
    - cron: '0 0 * * THU'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.3', '8.4']
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              tools: composer:v2
              php-version: ${{ matrix.php-versions }}
        - uses: actions/checkout@v4
        - uses: php-actions/composer@v6
          with:
              php_version: ${{ matrix.php-versions }}
              version: 2
        - run: XDEBUG_MODE=coverage ./vendor/bin/phpunit
        - name: Upload coverage results to Coveralls
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          run: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v
